curl: Add versioned-dep on libcurl-openssl4
Use a versioned dependency to make sure curl and
libcurl-openssl4 are always the same version.

It should technically be more correct for curl
to allow for newer libcurl-openssl4 versions,
but this likely to avoid more problems.

Example use case:

2bda4b8f8b0b:/work/packages# grep curl /etc/apk/world
libcurl-openssl4=8.12.0-r0
2bda4b8f8b0b:/work/packages# apk add curl
(1/1) Installing curl (8.12.0-r0)
Executing glibc-2.40-r8.trigger
Executing busybox-1.37.0-r0.trigger
OK: 34 MiB in 37 packages
2bda4b8f8b0b:/work/packages# apk add curl=8.12.0-r1
ERROR: unable to select packages:
libcurl-openssl4-8.12.0-r0:
breaks: curl-8.12.0-r1[libcurl-openssl4=8.12.0-r1]
satisfies: world[libcurl-openssl4=8.12.0-r0] curl-8.12.0-r1[so:libcurl.so.4]
2bda4b8f8b0b:/work/packages# apk add curl=8.12.0-r1 libcurl-openssl4=8.12.0-r1
(1/2) Upgrading libcurl-openssl4 (8.12.0-r0 -> 8.12.0-r1)
(2/2) Upgrading curl (8.12.0-r0 -> 8.12.0-r1)
Executing glibc-2.40-r8.trigger
Executing busybox-1.37.0-r0.trigger
OK: 34 MiB in 37 packages

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>